#define OCF_MAX_JSON_SIZE 1000

#define OCF_SERVO_IN_PIN 13
#define OCF_SERVO_IN_LOCKED 90
#define OCF_SERVO_IN_UNLOCKED 116
#define OCF_SERVO_OUT_PIN 12
#define OCF_SERVO_OUT_LOCKED 90
#define OCF_SERVO_OUT_UNLOCKED 66

#define OCF_MONTION_IN_PIN 32
#define OCF_MONTION_OUT_PIN 33

#define OCF_CLOSE_AFTER_MS 2000

