#include <OCFFlapControl.h>
#include <Arduino.h>

void OCFFlapControl::init(){
    OCFState::loadConfig();
    OCFState::loadCats();
    stateMachineOutside = new OCFStateMachine(OCFDirection::OUT);
    stateMachineInside = new OCFStateMachine(OCFDirection::IN);
}

void  OCFFlapControl::deinit(){

}

void  OCFFlapControl::loop(void* params){
    while(true){
        stateMachineInside->update();
        stateMachineOutside->update();
        delay(10);
        // Idea: collect events generated by both updates, aggregate them and run handlers (save, mqtt)
    }
}

OCFMachineStates OCFFlapControl::getInsideState(){
    return stateMachineInside->getState();
}
OCFMachineStates OCFFlapControl::getOutsideState(){
    return stateMachineOutside->getState();
}
